[build]
  publish = "public_html"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    name = "Contact Form"

[[plugins]]
  package = "@netlify/plugin-emails"

[[forms.contact.notifications]]
  to = "info@thegreaterworkshouse.org"
  from = "noreply@netlify.com"
  subject = "New Contact Form Submission"
