[build]
  publish = "public_html"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[forms]
  [forms.contact]
    name = "Contact Form"

[[forms.contact.notifications]]
  email = "info@greaterworkshouse.org"
